/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TrackingState implements org.apache.thrift.TEnum {
  Inferred(0),
  Tracked(1);

  private final int value;

  private TrackingState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TrackingState findByValue(int value) { 
    switch (value) {
      case 0:
        return Inferred;
      case 1:
        return Tracked;
      default:
        return null;
    }
  }
}
