/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class Hands : TBase
{
  private Hand _left;
  private Hand _right;

  public Hand Left
  {
    get
    {
      return _left;
    }
    set
    {
      __isset.left = true;
      this._left = value;
    }
  }

  public Hand Right
  {
    get
    {
      return _right;
    }
    set
    {
      __isset.right = true;
      this._right = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool left;
    public bool right;
  }

  public Hands() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Struct) {
            Left = new Hand();
            Left.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.Struct) {
            Right = new Hand();
            Right.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("Hands");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Left != null && __isset.left) {
      field.Name = "left";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Left.Write(oprot);
      oprot.WriteFieldEnd();
    }
    if (Right != null && __isset.right) {
      field.Name = "right";
      field.Type = TType.Struct;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      Right.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("Hands(");
    bool __first = true;
    if (Left != null && __isset.left) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Left: ");
      __sb.Append(Left== null ? "<null>" : Left.ToString());
    }
    if (Right != null && __isset.right) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Right: ");
      __sb.Append(Right== null ? "<null>" : Right.ToString());
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

